# step1

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [3]:
type(a)

numpy.ndarray

In [4]:
b = np.array([[1.5, 2, 3], [4, 5, 6]])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [5]:
b = np.array([[1.5, 2, 3], [4, 5, 6]], dtype=np.complex)
b

array([[1.5+0.j, 2. +0.j, 3. +0.j],
       [4. +0.j, 5. +0.j, 6. +0.j]])

In [6]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((2,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.empty((3, 3))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 6.24498976e-321],
       [1.06099790e-312, 8.70018274e-313, 8.45528066e-307]])

In [10]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [11]:
np.linspace(0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [12]:
print(np.arange(0, 5000, 1)) 

[   0    1    2 ... 4997 4998 4999]


## step2

базовые операции

In [13]:
a = np.array([20, 30, 40, 50])

In [14]:
b = np.arange(4)

In [15]:
a+b

array([20, 31, 42, 53])

In [16]:
a-b

array([20, 29, 38, 47])

In [17]:
a*b

array([  0,  30,  80, 150])

In [18]:
np.cos(a)

array([ 0.40808206,  0.15425145, -0.66693806,  0.96496603])

индексы, срезы, итерации

In [19]:
a=np.arange(10)**3

In [20]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [21]:
a[3:5]

array([27, 64], dtype=int32)

In [22]:
a[2:7]

array([  8,  27,  64, 125, 216], dtype=int32)